package dao;

import java.util.List;
import model.Actor;
import model.ActorExample;
import org.apache.ibatis.annotations.Param;

public interface ActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    long countByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    int deleteByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Short actor_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    int insert(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    int insertSelective(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    List<Actor> selectByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    Actor selectByPrimaryKey(Short actor_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Actor record, @Param("example") ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Actor record, @Param("example") ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Aug 20 11:57:25 GMT+08:00 2018
     */
    int updateByPrimaryKey(Actor record);
}